{% set version = "3.0.7" %}

package:
  name: pyparsing
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyparsing/pyparsing-{{ version }}.tar.gz
  sha256: 18ee9022775d270c55187733956460083db60b37d0d0fb357445f3094eed3eea

build:
  number: 0
  skip: True  # [py<36]
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6

test:
  imports:
    - pyparsing
  requires:
    - pip
    - python <3.10
  commands:
    - pip check

about:
  home: https://github.com/pyparsing/pyparsing/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create and execute simple grammars
  description: |
    The pyparsing module is an alternative approach to creating and executing
    simple grammars, vs. the traditional lex/yacc approach, or the use of
    regular expressions. The pyparsing module provides a library of classes
    that client code uses to construct the grammar directly in Python code.
  doc_url: https://github.com/pyparsing/pyparsing/blob/master/docs/HowToUsePyparsing.rst
  dev_url: https://github.com/pyparsing/pyparsing/

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
