travis:
  secure:
    BINSTAR_TOKEN: ik9h/WFDlAnUn4mok5F78EWd0xwLheFFy3MOQ823LlaVZvBTet8uh/1VThIeAwMJBTkA/ZrH3CXOAoS2C5FmlrXMCXUVn5iCkreliQ5gvKWT7d6pz4t24GbLyDOGeZQv+hcVa3nTamVRnPbRpN3c0iBULA3EhSDiz2EP13kb2H5GuC1KquOIyK7BZvCOSr9gJWcyeinhsEXfR3433Hjh3WJdrAE+CU7C0HDMXAuWNY+diO8t+Zy1BBI9VGdab7d5rlOm7TRSNSRUs3XXG2MkuEoN5jQrIdA/TZqOwccaK75VD04NltHeMVEZivZMsQxMqYgbBw/XZ6l1W+wci+JhkCq1TjABHVyR0BXt8DrBTpjMOYFpqNiM+GantKKcnZRvwE88WajGiGdOvzf6Zr+WIW+E6at9W4Odj4H7rO+A8EZZ8f/FimCC262N+5tG3Qcw++Qrbu5MHd1n6dfkS17j3Nnl2yS8RX4FubLTpUeFgJsKGltaIgjtk7yg43o79p4uPsglCVc/dIGNFNODppclW45pQxWnpm5fX03Jg2AIDQegajBTcxD1PZF5VEDtTtltyBNqChekzhL3Nr2kioGjKQ+RXdyYWsLdzxlKBdBvqd9qtKyPh0ApRIjf1CtKGWnRhWASFhKf/i5wtP8HWMP6qhSv2O4dH/kecFIBkCvKGYs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
