travis:
  secure:
    BINSTAR_TOKEN: EM8efDGXQQDrttzRYL+q1Bozb5wWjPYgiRPZK6fUSTqbiL7w/r5UCkC8iG+6gAGgb4Ga9sjtpqEG09cjprVtO07yZZEC7UgE5jtF5WcDPHqYFcG3JYKIlzw6K8nVzdJ+KrXUNjyLVnfN3j1EUZjNigUwyRkTwXnsfZLXvSCR/871J8Mc1PR4KnC2kG65/8LGSwW30yLhTTH7IYYumy0QI9uxX5DZ6FeWaNDRSHFIBqZdUyOrOIIBQM9Qqe9wgrTVnvfqUNI2ia4WNBYBEPDZCluPCt88LKZbZ7GPwX9PV+Aft/auXIBNGaLqvHFFcUtG/EFHXUr1nda3VnQE+1uHS0xRzKTuNvsT2D6Rn/ww13iFsfFcT+BQi5vvX9DxqRaegtiiCFldwFaYxj0PWsAJfEg8181htGaVPumkbad9d6D9J2vyAKbe5+mrdlI/Vnwqbkn0v0D2KRU5AzJ+0CzXwNiL9KqzpFFEEEcd020CBNb7snz9MiV5rkmoLYV1Pgsq0CIvuf+RfL6OSGuh63mD3VvJz3D5Ymqzs9dSqRGr1ihgPvaZdFngpQdHOWaHgJAXheQKx8Wfv5bxQd8uN053cmoDAclcDU0dRzZFMe0vIJq5P1j0K7cdd2dwpZssT2zEjWAWVvJnkjZ3HT4HU81Hqv3/ZdY1pVTKwEv9Rq0zf+4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
