travis:
  secure:
    BINSTAR_TOKEN: QN/mlq9P71RVtaeICkY+yPWSIZBt8+sKNdp7DUI5ziJLgttwLOQ6HxKF/19kYIM3v9T0KvLxrNa64lg4923xpfnoyPMhFGGfzH2DSB7ak6XoeqAITXU7DFouC/KsAUdbM+kMwvgNqcxI5BNwG9bBfE+xFi0s39i37EzOd9BpL+ZOAj7wpBSG+j78az5N+YTN1dZ7dkLBg0+4AOwK5S8ZnJU1QMh2nihkSPVtNEKSsTJN1jO44ABBN4uV3Qa5WETmS6rQR+kVGxIoKxRDfmLBl3QfH7wimw5hse5lMnp9S41u0iQ3471kW3ZsrsZbKaFEPkVyrQnfs2PfQgsjovq2VanTG1wb2wnAdTb7lfmCudsGaNsHw73GXD7LQVv8/xibwQiGyUsfOaD1jwsSUjR+WE6Vqdv7aaPxmMNUtBkYO8qf2hiUsBuX934oHIxOgu2fa7qyKyMaD9Jv4s0h6BIelw8C15abxziClYQORbDlZDuovaKK48vqj7xkYLLjBcf4K1o3Jh/6bDONwVvevdR4BtpADvdMFoThkWwXWZ6dtFWEBL3j6BFzr6XmubrQoqNfFewc4Odejre1ZaHj3HNgqFm0qn19XYyEI+5lyFFHkMys3ADQGAlq0uH5K5JYYb9NeUOiKpC//ITNvZ6ZMEOCGuo21rtxoqymqL0OAc3560Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
