travis:
  secure:
    BINSTAR_TOKEN: Ou4upBsrERho8aVdbob9lQkl3Y4dRpS6i+w87oucBXTILkM81HQ92RZ1l9dp48GjqwW0OqTTT4N34TSFYRmzeKikRyftRapaHUfE27ogSUWOpTP3C3VmThNhvDmBOuatiKc/IYn1mcK28dfO3PL5Yr2KkeHTL9D5DHkAuZgZIsnbYfVo7HVQKxOin63RCYXUodRYAKjdwdi0KP3C2rgW1mruFiH+mipYGvdMvGtSBc5Rdb8Yguoc1rY0vMuIUlsEA8+FlyrYNJ2C+v5Kf46NxszaNTenf1s+IQT6aunpXoKwJN0jLDiCSj1oVTGbkjHBoyjOHSpNtAGaqKh+Ac0L1Xt148tMZFk/E7vU6HRjawZ+kryN9VMupqPn7prQ8Rt9/CVr7kKpH5/aCc9lwr5DxSB4SllIehOb75jGlqanU8jq/FGXQzfcbvB5DbukVuRvSJZE16lSLzn8KVOG7rSGIoPbF2Ge3721Xk4kYHc+5HevKyx9YsvjLF1ICOLnY4QbqqBze/UmqQQnA2whMbRQ7MA0yXAwO7iFzCGqBg9/ZKVSn9NP5Hwp/OthmLoFVzZ9wAX41fMdi25jTwh5x+wJ79Ff1hHpl2eo0+8pH/To6DGphynxW/iO2IPHpMP38vyCwj0VnLG9rSUKVfWtLtSRTd96Wyj+iNHQ6o2I4XG+1Oc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
