travis:
  secure:
    BINSTAR_TOKEN: HbrNnbM5hLF4Y7fIw2c2ggrQLf4lMgXetazt1wLpdlDfTcKBTfXOvm61A78JCpu0dwHoOqbn6TqOtUxkbvScLO7/0ZW6vGiVEup32VQ0XSpl4c9T/Jp7L4wM+MsgLwtEmEH7RNKyE8sFH77ASKWQvo7cpMpKTh6PosP/TXac95t4KTrs+2bqXGSFVCzJHD3fHAaEZRPZpf5/KIhyzfeU0FtVU6cSlDP+fz6R/CmSVX7RmN99go7vUBs+eMKkxdGNYefJh7vJuSBCsyrDx49acwPgEzI3eEVqPnanKW6pUTDnijH1mnkO7mKICXNZxKzZU7UDxQk8A2eSF8owwdcLoWuPCqpHx5Mioz755nSLo83oIPxyTNTALUQkqhLu8W0Pwtk9Ir4pTlY7n95EMZliJ6hxbiekN7k2vUjmyZrvMu6OARR3dOUcA/AXHJ1wxccIKXO7cY820TF/9S4Pu0lxwmcx6B7zu1ZkN8FE4++sCy/iKgEC4itKU1Av2h/fMFC1SrXdgF23TlqOejFHNfL48ouqEhBOlu21wWpq9ERrAW+NEpdd+SoHOVJir9B+QX6HiiW+XqRepx50/vP9SWdLCWHbqSz8PeoDnt0geRRIah2JHonpg+23PDTFqQuE9xKqy0gdgvmYAOzgNZQh+iUX/TW+J+KfJTFQyfUe4uliQbY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
