travis:
  secure:
    BINSTAR_TOKEN: U3SPnY74JBmKxZRKmsrGJfy6DGFs/Li3iOcMsZyM9gwpTk1ymDH8JBfKDuQS30Wh2ByLaur6ef1gOEMGy4u9l3uhRyRvvrmYl/GE5v/clcOD+Ag3LZTvdI4FDTha1HZE7p8zjU7NBkYn8EjE/sP+UJzAGjv5kLlLuOjVlqaja0g0k/nwbqsS+rt6RPBoi39FGLA5o0W+cDzXmfBXpcfFe7rPUmFJ9jAJm8QZxBAlb7JzJRbwQGVbVBkDb6jrnOxZgwscCj0+Tnqmte8L5+ApJx868dClLTIuLPwQi0ee8YeJQ8vbeiDJ06vNwaA94BkP6tsQfyj9YkHGRmHYPs9JwFGtl/vMTzp9sZZOgXE35AIeh7fyAYQOk2JqKS44DhUwCEGUfDto9u764CmhpOeuKRH5ewRjhC0PKfzIlKdMpUCsPj4Wvk03qoapYVSeoe53FtOFo3ujv/ag5XqZFGPFjQUdFAgQoNARhm7gHRP9/DyFL2pcJv4fsXcRbG9G2RrWolThA9bg+CWJTT4gu4GOWuSnoF8XvUmeL+YwKQUU+8oD3/+N/rM8MUpGBCLyaGyI6yEJsdavR1cQ26niTQFfwgwWUKD8cH5Zx++SZz0BCX8O72/orIcLLLlLLqj1x/lnB/fZx830z9V7NFLHXAHcQ1UtXyEfxMhjViwh6VUQ8AE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
