travis:
  secure:
    BINSTAR_TOKEN: uJuLwDBobjcIKrvG7ekS5mWCqF68iDJ4lAYRFY77EITV+ryyNr5K9pcwRb8OV3A2UQI9Zqlj+5p+HGsvWpZ24z6vQbmm3leCEbVtGajZdUEzWzZ6P79FPM7yPrEvvXWDNXDdSi4i8/K0Tf/kqbckg1z78Mm18w7q2jr4q/eTP6Zz2NkLVq9V+sems+Yqo4ruFOngDqI64w6XQbo4OUSbAUYaadG5FSzyPq50z6pQhmXHPSu7MVgmoRZ5l2IeBQhlOKW0EwXX7lHg0sZkSJGYzJZIpmETHjgkJO8pyYKwZ2x0Y+GcNlsxZFM6IeqfAaKhf+TjZ3UTNlPnBFpKcUKmv2wvkoTYD3H/nspKWqVLry8gOJJYaPZqVuY8Q6M15eZmmQ63YE9V+d3e63KjMD7ohluNfN8j+Qs7KgzGkCO61WKilqffVPuhDiui8wbhROaOr6bRI7b9Z0z6clX/d6iBYD0dAMwoiThOLyyR+s1k/VM11p5h+cUv9oDEwdaL4nq51SElImrxSmamBh6FB1PJ7a3MtdpcOv7KP4uf7BcU3UeQYuA9oqm/sXAKaCrHj3AGfCC+76oex/TEIY7CRmKfMqTb4OuqOTm7BX56YTCnMHlo/2vERKECWGL09zaL50ajNvj/Aoy9TQQztdtXtojrxnquZYYoWl8h+PCqmpFZFUM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
