travis:
  secure:
    BINSTAR_TOKEN: pyRA72ApbDnx8ckmCEPWlPUCFa4QhyBRJlpJJah9CF0Y1H+UIZoOdeFtJtY2SkmUDhptM4PjvMwdsKU4CVyt0C8UtyLFDq0emBhYbCK1y/kzHMWSBLWPgut2ldEVbeBRCG7Yke13BG4jeaHvBVKqXjMtDoFCQ1GWCghXTzi3I0MrS93QQNck/bdSFNC7yd6W3ANk/iGLqMbSqodiK8WlktyjiloNthXrtgAnvflS1VPxdtEmGqx1tSw/fASfcTmXZoj2mcENf5oQUY57jhKtfEt/BN6FL6VRPPyTbq5iPsVhkmdg+prpjQmBaEAJaINTnE+RSOOVy62/a2YdXjRNRfi46HsnI2t6oKmLIYTaOtgPa7Vt9oaf+1IdIgHS2hxXzKirJtiwyqQ/AbK95/RUIfmInZ3WcBcNPHh1riks1qXxgZZiIzfaGh6Fi6e8hRwOJE5wJ6aDjj8AHZa2o5itRLPXxwVNXlWx7c5FJXKqk5t7LnC3lmrxOsGBuAXsjQr0UHxPnuBfcoXbhUKYe8F4CTMA2sG5EBQDWp0SLTedbPGe3lP7lbw8H2wMPRqNIJV+kBnQSLV1+UveCsOwxaDsd6TJD1rtRIDfqEVtfH+JAF+KYtTEDgStsKWAJFqg4FJPJTzLNTKEmBdsnwnGsRt+BHATw8lArU4T/241Zc9MVLI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
