travis:
  secure:
    BINSTAR_TOKEN: G6DK7itRsU+t5p5GzJX8rxIDI5jB94Ht2D3MMcTueJptI/jSnI2OvBLmSyHRwcDymb0mtmXVMsbNRKTHB5NH7odwh+7NlJan31hKQO0/2T0VZZLyDXhRNhB8SDHSZRTGDEDWb8avTImSr7cEPnW0/koxdbmK/sapiw3bwzFHeUkjeT+vVNYKX91KGdoh/imw4ogqdTUaXUtJjZlGJFTqnubpNT5M74TI+8UTrxObayw+wAdGE4/UJcYiFvO21bM5KtpdGKPKceMtvkxh69uGy060jKpj8ynvMtD1vOy+oihsjBI4qbibQzvf2yHe7W499ZEj1VVtlHbXKszak+UQ5fv4ws8owtQnkvOZ7+TezOHuWV1x/tiJzpUBRl+zKk12pi0ty/4uqUhvHkXP3b0viZJX4XiYu+lD1AjzGKrcHt689/Amcc/IEt8BDHg4GB6Wdj3XVbatgbhZCXl0H4f8q/BeOhAS7L04iclvKtVoCUWoKJ8Yj4F5jTNIPD31AgEOYBSO033W5MjkZzaDj9jg6qG/YhtwPh9WSoD0gckWH3vlv3pxAdf4/YFHOJ4Amid4/fwBhK8wGNAiXFuchskQiJ+BIvIyFAGYINlWEdHniZGS4ZEcK3aE2MidnTmYO/q42vzvgYTFzHja2WRGWJYk53SBofmQfyC0u0X9J9Mc784=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
